/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package flex2.compiler.mxml;

public interface ParserConstants {

  int EOF = 0;
  int START_DESIGNLAYER = 1;
  int END_DESIGNLAYER = 2;
  int START_DECLARATIONS = 3;
  int END_DECLARATIONS = 4;
  int START_STYLE = 5;
  int END_STYLE = 6;
  int START_SCRIPT = 7;
  int END_SCRIPT = 8;
  int START_METADATA = 9;
  int END_METADATA = 10;
  int START_STATE = 11;
  int END_STATE = 12;
  int START_MODEL = 13;
  int END_MODEL = 14;
  int START_XML = 15;
  int END_XML = 16;
  int START_XMLLIST = 17;
  int END_XMLLIST = 18;
  int START_ARRAY = 19;
  int END_ARRAY = 20;
  int START_VECTOR = 21;
  int END_VECTOR = 22;
  int START_BINDING = 23;
  int END_BINDING = 24;
  int START_STRING = 25;
  int END_STRING = 26;
  int START_NUMBER = 27;
  int END_NUMBER = 28;
  int START_INT = 29;
  int END_INT = 30;
  int START_UINT = 31;
  int END_UINT = 32;
  int START_BOOLEAN = 33;
  int END_BOOLEAN = 34;
  int START_CLASS = 35;
  int END_CLASS = 36;
  int START_FUNCTION = 37;
  int END_FUNCTION = 38;
  int START_REMOTEOBJECT = 39;
  int END_REMOTEOBJECT = 40;
  int START_METHOD = 41;
  int END_METHOD = 42;
  int START_ARGUMENTS = 43;
  int END_ARGUMENTS = 44;
  int START_WEBSERVICE = 45;
  int END_WEBSERVICE = 46;
  int START_OPERATION = 47;
  int END_OPERATION = 48;
  int START_REQUEST = 49;
  int END_REQUEST = 50;
  int START_HTTPSERVICE = 51;
  int END_HTTPSERVICE = 52;
  int START_COMPONENT = 53;
  int END_COMPONENT = 54;
  int START_REPARENT = 55;
  int END_REPARENT = 56;
  int START_PRIVATE = 57;
  int END_PRIVATE = 58;
  int START_LIBRARY = 59;
  int END_LIBRARY = 60;
  int START_DEFINITION = 61;
  int END_DEFINITION = 62;
  int START_ELEMENT = 63;
  int CDATA = 64;
  int END_ELEMENT = 65;
  int SKIP_ELEMENT = 66;

  String[] tokenImage = {
    "<EOF>",
    "<START_ELEMENT>",
    "<CDATA>",
    "<END_ELEMENT>",
    "DesignLayer",
    "/DesignLayer",
    "Declarations",
    "/Declarations",
    "Style",
    "/Style",
    "Script",
    "/Script",
    "Metadata",
    "/Metadata",
    "State",
    "/State",
    "Model",
    "/Model",
    "XML",
    "/XML",
    "XMLList",
    "/XMLList",
    "Array",
    "/Array",
    "Vector",
    "/Vector",
    "Binding",
    "/Binding",
    "String",
    "/String",
    "Number",
    "/Number",
    "int",
    "/int",
    "uint",
    "/uint",
    "Boolean",
    "/Boolean",
    "Class",
    "/Class",
    "Function",
    "/Function",
    "RemoteObject",
    "/RemoteObject",
    "method",
    "/method",
    "arguments",
    "/arguments",
    "WebService",
    "/WebService",
    "operation",
    "/operation",
    "request",
    "/request",
    "HTTPService",
    "/HTTPService",
    "Component",
    "/Component",
    "Reparent",
    "/Reparent",
    "Private",
    "<SKIP_ELEMENT>",
    "/Private",
    "Library",
    "/Library",
    "Definition",
    "/Definition",
  };

}
