////////////////////////////////////////////////////////////////////////////////
//
//  ADOBE SYSTEMS INCORPORATED
//  Copyright 2005-2008 Adobe Systems Incorporated
//  All Rights Reserved.
//
//  NOTICE: Adobe permits you to use, modify, and distribute this file
//  in accordance with the terms of the license agreement accompanying it.
//
////////////////////////////////////////////////////////////////////////////////

package flex2.compiler.mxml.rep.decl;

/**
 *
 */
public interface PropertyDeclaration
{
	int getLineRef();

	String getName();

	String getTypeExpr();

	boolean getInspectable();

	boolean getTopLevel();

	boolean getIdIsAutogenerated();
	
	String getComment();
}
